from . import help
from . import start
from . import admin
from . import xizmatlar
from . import back
from . import tmebot
from . import nazad
from . import sayt
from . import video
from . import moushin
from . import grafik
from . import canal
from . import buyurtma
from . import yesss
from . import noo
from . import zakazat
